TOPICS:
        Duplicate
        pd.concat
        duplicated()
        drop_duplicates()

In [2]:
import pandas as pd
data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

df = pd.DataFrame(data)

In [3]:
print(df)

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [5]:
#duplicate value banana, we use concat function:to merge 2 data frame , humari rows 10 se 12 ho gai duplicate 
#records aa gaye iss liye, ignore index true matlab purana index bhul jaao new index se dekho.
df_duplicate =pd.concat([df,df.iloc[[2,5]]],ignore_index=True)
df_duplicate #print kiya

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0          101   25    Male  Cardiology  Nagpur           50000              5
1          102   45  Female   Neurology    Pune           35000              3
2          103   35    Male  Cardiology  Nagpur           60000              6
3          104   60  Female  Orthopedic  Mumbai           45000              4
4          105   50    Male   Neurology    Pune           30000              2
5          106   28  Female  Cardiology  Nagpur           55000              5
6          107   65    Male  Orthopedic  Mumbai           70000              7
7          108   40  Female   Neurology    Pune           40000              3
8          109   55    Male  Cardiology  Nagpur           65000              6
9          110   30  Female  Orthopedic  Mumbai           50000              4
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

pd.concat(): dataframes ko jodne ka kaam karta hai
iloc[[2,5]] row 2 our row 5 select karna
ignore_index = True--->index ko fresh nummbering denga new no

In [ ]:
#agar dataframe me 10 rows hai or hum df.iloc[[2,5]]se 2 rows ko or add kar rhe hai toh total kitni row hongi
#ans:12 rows

#aur konsi row duplicate hongi?
#ans:patient_id-- 103,106

In [6]:
#imagin karo hospital ke database me patient 103 ka same record do baar aa gya. ab hospital ke total patients
#count karenge to kya honga?
#use duplicated function(): duplicate hai ya nhi ye janne ke liye ye use karte hain.
df_duplicate.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [7]:
#sirf duplicate row dekhne ke liye
df_duplicate[df_duplicate.duplicated()]

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [8]:
#duplicate record hatane ke liye
df_clean = df_duplicate.drop_duplicates()
df_clean #purana data frame vapas aa gya

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [9]:
df_clean.shape #kitni rows hai dekhne ke liye

(10, 7)

duplicated() :identify duplicate values
drop_duplicates() :duplicate ko remove karta hai

In [10]:
#patient 103 do baar hai to kya dono record delete honge kya ------>NO


#patient id same hai but tratment cost alag hai to duplicate honga kya ---->NO
df_duplicate.duplicated(subset=["Patient_ID"]) #duplicate value true ho jayngi

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [11]:
#abb duplicate value hatane ke liye
df_duplicate.drop_duplicates(subset=["Patient_ID"])

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

#