In [1]:
import pandas as pd

In [2]:
df_test={
    "Patient_ID":[1,2,3],
    "Age":[34,54,29],
    "Surgery_Type":["eye","heart","brain"]
}
df=pd.DataFrame(df_test)

In [3]:
print(df)

   Patient_ID  Age Surgery_Type
0           1   34          eye
1           2   54        heart
2           3   29        brain

In [4]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],
    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [5]:
print(df.head(5))

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned

In [6]:
print(df["Patient_ID"]) 
print(df["Surgery_Type"]) 
print(df["Admission_Type"])

0    P101
1    P102
2    P103
3    P104
4    P105
5    P106
6    P107
7    P108
8    P109
9    P110
Name: Patient_ID, dtype: str
0     Cholecystectomy
1                CABG
2        Appendectomy
3       Hernia Repair
4    Knee Replacement
5                PTCA
6        Appendectomy
7     Cholecystectomy
8       Hernia Repair
9    Knee Replacement
Name: Surgery_Type, dtype: str
0      Planned
1    Emergency
2    Emergency
3      Planned
4      Planned
5    Emergency
6    Emergency
7      Planned
8      Planned
9      Planned
Name: Admission_Type, dtype: str

In [7]:
df[df["Admission_Type"]=="Emergency"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency

In [8]:
df[df["Operation_Duration_Min"]>150]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [14]:
(df[df["City"]=="Hyderabad"][["Patient_ID","Age","Surgery_Type","Admission_Type"]])

  Patient_ID  Age      Surgery_Type Admission_Type
0       P101   45   Cholecystectomy        Planned
2       P103   34      Appendectomy      Emergency
4       P105   41  Knee Replacement        Planned
6       P107   29      Appendectomy      Emergency
8       P109   47     Hernia Repair        Planned

In [9]:
df["Operation_Duration_Min"].mean()

np.float64(133.0)

In [10]:
df["Operation_Duration_Min"].max()

np.int64(240)

In [11]:
df.loc[df["Operation_Duration_Min"].idxmax()]

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [ ]:
(df["Operation_Duration_Min"]>100) & (df["Length_of_Stay_Days"]>3)

0    False
1     True
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9     True
dtype: bool

In [13]:
df[df["Operation_Duration_Min"]=="Emergency">100]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().